version: '3.8'
services:
  redis:
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - 8081:8081
    depends_on:
      - redis
