version: '3.8'
services:
  customers-api:
    container_name: customers-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - ${APP_PORT}
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - redis
volumes:
  redis_volume:
