version: '3.8'
services:
  redis:
    image: redis:7.0.11
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_volume:/var/lib/redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - 8081:8081
volumes:
  redis_volume:
